coverage:
  precision: 2
  round: down
  range: 80...100

comment:
  layout: diff, files
  behavior: default  # update, if exists. Otherwise post new.
  require_changes: true  # only post the comment if coverage changes
  require_base: no
  require_head: yes

flags:
  package-cli:
    paths:
      - packages/cli/**/*.ts
    carryforward: false
  package-core:
    paths:
      - packages/core/**/*.ts
    carryforward: true
  package-testing:
    paths:
      - packages/testing/**/*.ts
    carryforward: true

ignore:
  - scripts/
  - testdata/
