coverage:
  precision: 2
  round: down
  range: 80...100

comment:
  layout: diff, flags, files
  behavior: default  # update, if exists. Otherwise post new.
  require_changes: true  # only post the comment if coverage changes
  require_base: no
  require_head: yes

flags:
  package-benchmarking:
    paths:
      - packages/benchmarking/**/*.ts
    carryforward: true
  package-cli:
    paths:
      - packages/cli/**/*.ts
    carryforward: true
  package-core:
    paths:
      - packages/core/**/*.ts
    carryforward: true
  package-language-css:
    paths:
      - packages/language-css/**/*.ts
    carryforward: true
  package-language-html:
    paths:
      - packages/language-html/**/*.ts
    carryforward: true
  package-language-js:
    paths:
      - packages/language-js/**/*.ts
    carryforward: true
  package-language-utils:
    paths:
      - packages/language-utils/**/*.ts
    carryforward: true
  package-testing:
    paths:
      - packages/testing/**/*.ts
    carryforward: true

ignore:
  - scripts/
  - testdata/
