# Check out Nyc at: https://github.com/istanbuljs/nyc

all: true
extends:
  - "@istanbuljs/nyc-config-typescript"
reporter:
  - lcov
  - text

check-coverage: true
statements: 85
lines: 85
branches: 80
functions: 85
watermarks:
  statements: [85, 95]
  lines: [85, 95]
  branches: [80, 95]
  functions: [85, 95]

extensions:
  - .ts
include:
  - packages/**/*.ts
exclude:
  - _reports/
  - .temp/
  - node_modules/
  - packages/**/*.test.ts
  - packages/**/*.mock.ts

report-dir: ./_reports
temp-dir: ./.temp/nyc
