name: Code Analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 3"

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1.0.18
        with:
          config-file: ./.github/codeql.yml
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1.0.18
