name: Analyse Source Code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "packages/**"
  schedule:
    - cron: "0 7 * * 3"

permissions: read-all

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Initialize CodeQL
        uses: github/codeql-action/init@678fc3afe258fb2e0cdc165ccf77b85719de7b3c # v2.1.33
        with:
          config-file: ./.github/codeql.yml
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@678fc3afe258fb2e0cdc165ccf77b85719de7b3c # v2.1.33
