name: Validate Source Code
on:
  pull_request: ~
  push:
    branches:
      - main

permissions: read-all

jobs:
  changes:
    name: Determine jobs
    runs-on: ubuntu-latest
    outputs:
      all-packages: ${{ steps.all-filter.outputs.changes }}
      e2e-packages: ${{ steps.e2e-filter.outputs.changes }}
      integration-packages: ${{ steps.integration-filter.outputs.changes }}
      mutation-packages: ${{ steps.mutation-filter.outputs.changes }}
      performance-packages: ${{ steps.performance-filter.outputs.changes }}
      unit-packages: ${{ steps.unit-filter.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install Node.js
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Get filters string for all packages
        id: all-filters
        run: |
          export FILTERS=$( \
            node scripts/ci/get-filters.js all ${{ github.ref }} \
          )
          echo 'filters<<EOF' >> $GITHUB_OUTPUT
          echo "$FILTERS" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Check for file changes in all packages
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # tag=v2.11.1
        id: all-filter
        with:
          filters: |
            ${{ steps.all-filters.outputs.filters }}
      - name: Get filters string for e2e testing job
        id: e2e-filters
        run: |
          export FILTERS=$( \
            node scripts/ci/get-filters.js e2e ${{ github.ref }} \
          )
          echo 'filters<<EOF' >> $GITHUB_OUTPUT
          echo "$FILTERS" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Check for file changes in e2e tested packages
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # tag=v2.11.1
        id: e2e-filter
        with:
          filters: |
            ${{ steps.e2e-filters.outputs.filters }}
      - name: Get filters string for performance testing job
        id: performance-filters
        run: |
          export FILTERS=$( \
            node scripts/ci/get-filters.js performance ${{ github.ref }} \
          )
          echo 'filters<<EOF' >> $GITHUB_OUTPUT
          echo "$FILTERS" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Check for file changes in performance tested packages
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # tag=v2.11.1
        id: performance-filter
        with:
          filters: |
            ${{ steps.performance-filters.outputs.filters }}
      - name: Get filters string for mutation testing job
        id: mutation-filters
        run: |
          export FILTERS=$(node scripts/ci/get-filters.js mutation)
          echo 'filters<<EOF' >> $GITHUB_OUTPUT
          echo "$FILTERS" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Check for file changes in mutation tested packages
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # tag=v2.11.1
        id: mutation-filter
        with:
          filters: |
            ${{ steps.mutation-filters.outputs.filters }}
      - name: Get filters string for unit job
        id: unit-filters
        run: |
          export FILTERS=$( \
            node scripts/ci/get-filters.js unit ${{ github.ref }} \
          )
          echo 'filters<<EOF' >> $GITHUB_OUTPUT
          echo "$FILTERS" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Check for file changes in unit tested packages
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # tag=v2.11.1
        id: unit-filter
        with:
          filters: |
            ${{ steps.unit-filters.outputs.filters }}
      - name: Get filters string for integration job
        id: integration-filters
        run: |
          export FILTERS=$( \
            node scripts/ci/get-filters.js integration ${{ github.ref }} \
          )
          echo 'filters<<EOF' >> $GITHUB_OUTPUT
          echo "$FILTERS" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Check for file changes in integration tested packages
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # tag=v2.11.1
        id: integration-filter
        with:
          filters: |
            ${{ steps.integration-filters.outputs.filters }}
  test-performance:
    name: Performance
    runs-on: ubuntu-latest
    needs:
      - changes
      - compile
      - test-integration
    if: ${{ needs.changes.outputs.performance-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.performance-packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Cache compiled package
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: |
            packages/*/build
            packages/*/lib
            packages/*/tsconfig.tsbuildinfo
          key: >-
            compiled
            ${{ matrix.package }}
            ${{ hashFiles(format('packages/{0}/src/**', matrix.package)) }}
          restore-keys: |
            compiled ${{ matrix.package }}
      - name: Install Node.js
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run performance tests for packages/${{ matrix.package }}
        run: npm run test:performance -- ${{ matrix.package }}
  compile:
    name: Compile
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.all-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.all-packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Cache compiled package
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: |
            packages/*/build
            packages/*/lib
            packages/*/tsconfig.tsbuildinfo
          key: >-
            compiled
            ${{ matrix.package }}
            ${{ hashFiles(format('packages/{0}/src/**', matrix.package)) }}
          restore-keys: |
            compiled ${{ matrix.package }}
      - name: Install Node.js
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Compile packages/${{ matrix.package }}
        run: npm run compile --workspace=packages/${{ matrix.package }}
  test-unit:
    name: Unit
    runs-on: ubuntu-latest
    needs:
      - changes
      - compile
    if: ${{ needs.changes.outputs.unit-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.unit-packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Cache compiled package
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: |
            packages/*/build
            packages/*/lib
            packages/*/tsconfig.tsbuildinfo
          key: >-
            compiled
            ${{ matrix.package }}
            ${{ hashFiles(format('packages/{0}/src/**', matrix.package)) }}
          restore-keys: |
            compiled ${{ matrix.package }}
      - name: Install Node.js
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests for packages/${{ matrix.package }}
        run: npm run coverage -- ${{ matrix.package }} --unit
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        if: ${{ always() }}
        with:
          file: ./_reports/coverage/unit/${{ matrix.package }}/lcov.info
          flags: package-${{ matrix.package }}
  test-integration:
    name: Integration
    runs-on: ubuntu-latest
    needs:
      - changes
      - compile
      - test-unit
    if: ${{ needs.changes.outputs.integration-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.integration-packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Cache compiled package
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: |
            packages/*/build
            packages/*/lib
            packages/*/tsconfig.tsbuildinfo
          key: >-
            compiled
            ${{ matrix.package }}
            ${{ hashFiles(format('packages/{0}/src/**', matrix.package)) }}
          restore-keys: |
            compiled ${{ matrix.package }}
      - name: Install Node.js
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run integration tests for packages/${{ matrix.package }}
        run: npm run test -- ${{ matrix.package }} --integration
  test-e2e:
    name: End-to-end
    runs-on: ubuntu-latest
    needs:
      - changes
      - compile
      - test-integration
    if: ${{ needs.changes.outputs.e2e-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.e2e-packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Cache compiled packages
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: |
            packages/*/build
            packages/*/lib
            packages/*/tsconfig.tsbuildinfo
          key: >-
            compiled
            all
            ${{ hashFiles('packages/*/src/**') }}
          restore-keys: |
            compiled all
      - name: Install Node.js
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run e2e test suite for packages/${{ matrix.package }}
        run: npm run test -- ${{ matrix.package }} --e2e
  test-mutation:
    name: Mutation
    runs-on: ubuntu-latest
    needs:
      - changes
      - compile
      - test-unit
    if: ${{ needs.changes.outputs.mutation-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.mutation-packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Cache compiled packages
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: |
            packages/*/build
            packages/*/lib
            packages/*/tsconfig.tsbuildinfo
          key: >-
            compiled
            all
            ${{ hashFiles('packages/*/src/**') }}
          restore-keys: |
            compiled all
      - name: Cache incremental data
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: .cache/mutation/${{ matrix.package }}.json
          key: >-
            mutation
            incremental
            ${{ matrix.package }}
            ${{ github.run_number }}
          restore-keys: |
            mutation incremental ${{ matrix.package }}
      - name: Install Node.js
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run mutation tests for packages/${{ matrix.package }}
        run: npm run test:mutation -- ${{ matrix.package }}
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
