name: Validate Source Code
on:
  pull_request: ~
  push:
    branches:
      - main

permissions: read-all

jobs:
  changes:
    name: Determine jobs
    runs-on: ubuntu-latest
    outputs:
      all-packages: ${{ steps.all-filter.outputs.changes }}
      e2e-packages: ${{ steps.e2e-filter.outputs.changes }}
      mutation-packages: ${{ steps.mutation-filter.outputs.changes }}
      performance-packages: ${{ steps.performance-filter.outputs.changes }}
      tested-packages: ${{ steps.tested-filter.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Install Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Get filters string for all packages
        id: all-filters
        run: |
          export FILTERS=$( \
            node scripts/ci/get-filters.js all ${{ github.ref }} \
          )
          FILTERS="${FILTERS//'%'/'%25'}"
          FILTERS="${FILTERS//$'\n'/'%0A'}"
          FILTERS="${FILTERS//$'\r'/'%0D'}"
          echo "::set-output name=filters::$FILTERS"
      - name: Check for file changes in all packages
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # tag=v2.11.1
        id: all-filter
        with:
          filters: |
            ${{ steps.all-filters.outputs.filters }}
      - name: Get filters string for e2e testing job
        id: e2e-filters
        run: |
          export FILTERS=$( \
            node scripts/ci/get-filters.js e2e ${{ github.ref }} \
          )
          FILTERS="${FILTERS//'%'/'%25'}"
          FILTERS="${FILTERS//$'\n'/'%0A'}"
          FILTERS="${FILTERS//$'\r'/'%0D'}"
          echo "::set-output name=filters::$FILTERS"
      - name: Check for file changes in e2e tested packages
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # tag=v2.11.1
        id: e2e-filter
        with:
          filters: |
            ${{ steps.e2e-filters.outputs.filters }}
      - name: Get filters string for performance testing job
        id: performance-filters
        run: |
          export FILTERS=$( \
            node scripts/ci/get-filters.js performance ${{ github.ref }} \
          )
          FILTERS="${FILTERS//'%'/'%25'}"
          FILTERS="${FILTERS//$'\n'/'%0A'}"
          FILTERS="${FILTERS//$'\r'/'%0D'}"
          echo "::set-output name=filters::$FILTERS"
      - name: Check for file changes in performance tested packages
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # tag=v2.11.1
        id: performance-filter
        with:
          filters: |
            ${{ steps.performance-filters.outputs.filters }}
      - name: Get filters string for mutation testing job
        id: mutation-filters
        run: |
          export FILTERS=$(node scripts/ci/get-filters.js mutation)
          FILTERS="${FILTERS//'%'/'%25'}"
          FILTERS="${FILTERS//$'\n'/'%0A'}"
          FILTERS="${FILTERS//$'\r'/'%0D'}"
          echo "::set-output name=filters::$FILTERS"
      - name: Check for file changes in mutation tested packages
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # tag=v2.11.1
        id: mutation-filter
        with:
          filters: |
            ${{ steps.mutation-filters.outputs.filters }}
      - name: Get filters string for test job
        id: tested-filters
        run: |
          export FILTERS=$( \
            node scripts/ci/get-filters.js test ${{ github.ref }} \
          )
          FILTERS="${FILTERS//'%'/'%25'}"
          FILTERS="${FILTERS//$'\n'/'%0A'}"
          FILTERS="${FILTERS//$'\r'/'%0D'}"
          echo "::set-output name=filters::$FILTERS"
      - name: Check for file changes in tested packages
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # tag=v2.11.1
        id: tested-filter
        with:
          filters: |
            ${{ steps.tested-filters.outputs.filters }}
  test-performance:
    name: Performance
    runs-on: ubuntu-latest
    needs:
      - changes
      - compile
      - test
    if: ${{ needs.changes.outputs.performance-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.performance-packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Cache compiled package
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
        with:
          path: |
            packages/*/build
            packages/*/lib
            packages/*/tsconfig.tsbuildinfo
          key: >-
            compiled
            ${{ matrix.package }}
            ${{ hashFiles(format('packages/{0}/src/**', matrix.package)) }}
          restore-keys: |
            compiled ${{ matrix.package }}
      - name: Install Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run performance tests for packages/${{ matrix.package }}
        run: npm run test:performance -- ${{ matrix.package }}
  compile:
    name: Compile
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.all-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.all-packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Cache compiled package
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
        with:
          path: |
            packages/*/build
            packages/*/lib
            packages/*/tsconfig.tsbuildinfo
          key: >-
            compiled
            ${{ matrix.package }}
            ${{ hashFiles(format('packages/{0}/src/**', matrix.package)) }}
          restore-keys: |
            compiled ${{ matrix.package }}
      - name: Install Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Compile packages/${{ matrix.package }}
        run: npm run compile --workspace=packages/${{ matrix.package }}
  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - changes
      - compile
    if: ${{ needs.changes.outputs.tested-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.tested-packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Cache compiled package
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
        with:
          path: |
            packages/*/build
            packages/*/lib
            packages/*/tsconfig.tsbuildinfo
          key: >-
            compiled
            ${{ matrix.package }}
            ${{ hashFiles(format('packages/{0}/src/**', matrix.package)) }}
          restore-keys: |
            compiled ${{ matrix.package }}
      - name: Install Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run test suite for packages/${{ matrix.package }}
        run: npm run coverage -- ${{ matrix.package }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3.1.1
        if: ${{ always() }}
        with:
          file: ./_reports/coverage/${{ matrix.package }}/lcov.info
          flags: package-${{ matrix.package }}
  test-e2e:
    name: End-to-end
    runs-on: ubuntu-latest
    needs:
      - changes
      - compile
      - test
    if: ${{ needs.changes.outputs.e2e-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.e2e-packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Cache compiled packages
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
        with:
          path: |
            packages/*/build
            packages/*/lib
            packages/*/tsconfig.tsbuildinfo
          key: >-
            e2e
            ${{ hashFiles('packages/*/src/**') }}
          restore-keys: |
            e2e
      - name: Install Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run e2e test suite for packages/${{ matrix.package }}
        run: npm run test -- ${{ matrix.package }} --e2e
  test-mutation:
    name: Mutation
    runs-on: ubuntu-latest
    needs:
      - changes
      - compile
      - test
    if: ${{ needs.changes.outputs.mutation-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.mutation-packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Cache compiled package
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
        with:
          path: |
            packages/*/build
            packages/*/lib
            packages/*/tsconfig.tsbuildinfo
          key: >-
            mutation
            compiled
            ${{ hashFiles('packages/*/src/**') }}
          restore-keys: |
            mutation compiled
      - name: Cache incremental data
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
        with:
          path: .cache/mutation/${{ matrix.package }}.json
          key: >-
            mutation
            incremental
            ${{ matrix.package }}
            ${{ github.run_number }}
          restore-keys: |
            mutation incremental ${{ matrix.package }}
      - name: Install Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run mutation tests for packages/${{ matrix.package }}
        run: npm run test:mutation -- ${{ matrix.package }}
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
