name: Validate Configurations
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/codecov.yml
      - .github/renovate.json

permissions: read-all

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Validate .github/codecov.yml
        uses: ericcornelissen/codecov-config-validator-action@79ec876b95be6b652c76279cd8f8f47c68559d3b # v1.0.1
        with:
          file: .github/codecov.yml
  renovate-bot:
    name: RenovateBot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Install Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version-file: .nvmrc
      - name: Install Renovate CLI
        run: npm install -g renovate
      - name: Validate .github/renovate.json
        run: renovate-config-validator
