name: Validate Configurations
on:
  push:
    branch:
    - main
  pull_request:
    branches:
    - main
    paths:
    - '.github/codecov.yml'
    - '.github/renovate.json5'

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Validate .github/codecov.yml
      run: |
        RESULT=$(curl -s -o /dev/null -w "%{http_code}" --data-binary @./.github/codecov.yml https://codecov.io/validate)
        if ! [[ $RESULT == "200" ]]; then
          exit 1
        fi
  renovate-bot:
    name: RenovateBot
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: Install Renovate CLI
      run: npm install -g renovate
    - name: Validate .github/renovate.yml
      run: renovate-config-validator
