name: Lint
on:
  pull_request: ~
  push:
    branches:
      - main

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0
      - name: Cache compiled packages
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: |
            packages/*/build
            packages/*/lib
            packages/*/tsconfig.tsbuildinfo
          key: >-
            compiled
            all
            ${{ hashFiles('packages/*/src/**') }}
          restore-keys: |
            compiled all
      - name: Fetch main branch
        if: ${{ github.ref != 'refs/heads/main' }}
        run: git fetch origin main:main
      - name: Install Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Compile all packages
        run: npm run compile --workspaces
      - name: Run linters
        run: npm run lint
