name: Lint
on:
  - pull_request
  - push

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: Fetch main branch
        if: ${{ github.ref != 'refs/heads/main' }}
        run: git fetch origin main:main
      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run linters
        run: npm run lint
