# NOTICE:
# THIS WORKFLOW IS GENERATED AND SHOULD NOT BE EDITED MANUALLY.
name: Validate package cli
on:
  push:
    branches:
      - main
    paths:
      - "packages/cli/**"
  pull_request:
    paths:
      - "packages/cli/**"
jobs:
  compile:
    name: Compile package cli
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15.14.0
          cache: npm
      - name: Install monorepo dependencies
        working-directory: ./
        run: npm ci
      - name: Install packages/cli dependencies
        working-directory: ./packages/cli
        run: npm ci
      - name: Compile packages/cli
        working-directory: packages/cli
        run: npm run compile
  test:
    name: Test package cli
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15.14.0
          cache: npm
      - name: Install monorepo dependencies
        working-directory: ./
        run: npm ci
      - name: Install packages/cli dependencies
        working-directory: ./packages/cli
        run: npm ci
      - name: Run test suite for packages/cli
        run: npm run coverage -- cli
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./_reports/coverage/lcov.info
          flags: package-cli
