name: Validate Source Code
on:
  - push
  - pull_request

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    needs: [test]
    strategy:
      matrix:
        package:
          - core
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            changed:
              - 'packages/${{ matrix.package }}/**'
      - name: Use Node.js 12.x
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install monorepo dependencies
        if: steps.changes.outputs.changed == 'true'
        run: npm ci
      - name: Install packages/${{ matrix.package }} dependencies
        working-directory: ./packages/${{ matrix.package }}
        if: steps.changes.outputs.changed == 'true'
        run: npm ci
      - name: Compile packages/${{ matrix.package }}
        working-directory: ./packages/${{ matrix.package }}
        if: steps.changes.outputs.changed == 'true'
        run: npm run compile
      - name: Run benchmarks for packages/${{ matrix.package }}
        if: steps.changes.outputs.changed == 'true'
        run: npm run benchmark:${{ matrix.package }}
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - benchmarking
          - cli
          - core
          - testing
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            changed:
              - 'packages/${{ matrix.package }}/**'
      - name: Use Node.js 12.x
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install monorepo dependencies
        working-directory: ./
        if: steps.changes.outputs.changed == 'true'
        run: npm ci
      - name: Install packages/${{ matrix.package }} dependencies
        if: steps.changes.outputs.changed == 'true'
        run: npm ci
      - name: Compile packages/${{ matrix.package }}
        if: steps.changes.outputs.changed == 'true'
        run: npm run compile
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install monorepo dependencies
        run: npm ci
      - name: Run linters
        run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        package:
          - benchmarking
          - cli
          - core
          - testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            changed:
              - 'packages/${{ matrix.package }}/**'
      - name: Use Node.js 12.x
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install monorepo dependencies
        if: steps.changes.outputs.changed == 'true'
        run: npm ci
      - name: Install packages/${{ matrix.package }} dependencies
        working-directory: ./packages/${{ matrix.package }}
        if: steps.changes.outputs.changed == 'true'
        run: npm ci
      - name: Compile packages/${{ matrix.package }}
        working-directory: ./packages/${{ matrix.package }}
        if: steps.changes.outputs.changed == 'true'
        run: npm run compile
      - name: Run test suite for packages/${{ matrix.package }}
        if: steps.changes.outputs.changed == 'true'
        run: npm run coverage:${{ matrix.package }}
      - name: Upload coverage to Codecov
        if: steps.changes.outputs.changed == 'true'
        uses: codecov/codecov-action@v1
        with:
          file: ./_reports/lcov.info
          flags: package-${{ matrix.package }}
