name: Validate Source Code
on:
  - push
  - pull_request

jobs:
  changes:
    name: Detect changed packages
    runs-on: ubuntu-latest
    outputs:
      all-packages: ${{ steps.all-filter.outputs.changes }}
      benchmarked-packages: ${{ steps.benchmarked-filter.outputs.changes }}
      tested-packages: ${{ steps.tested-filter.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15.14.0
          cache: npm
      - name: Get filters string for all packages
        id: all-filters
        run: |
          export FILTERS=$(node scripts/ci/get-filters.js all)
          FILTERS="${FILTERS//'%'/'%25'}"
          FILTERS="${FILTERS//$'\n'/'%0A'}"
          FILTERS="${FILTERS//$'\r'/'%0D'}"
          echo "::set-output name=filters::$FILTERS"
      - name: Check for file changes in all packages
        uses: dorny/paths-filter@v2
        id: all-filter
        with:
          filters: |
            ${{ steps.all-filters.outputs.filters }}
      - name: Get filters string for benchmark job
        id: benchmarked-filters
        run: |
          export FILTERS=$(node scripts/ci/get-filters.js benchmark)
          FILTERS="${FILTERS//'%'/'%25'}"
          FILTERS="${FILTERS//$'\n'/'%0A'}"
          FILTERS="${FILTERS//$'\r'/'%0D'}"
          echo "::set-output name=filters::$FILTERS"
      - name: Check for file changes in benchmarked packages
        uses: dorny/paths-filter@v2
        id: benchmarked-filter
        with:
          filters: |
            ${{ steps.benchmarked-filters.outputs.filters }}
      - name: Get filters string for test job
        id: tested-filters
        run: |
          export FILTERS=$(node scripts/ci/get-filters.js test)
          FILTERS="${FILTERS//'%'/'%25'}"
          FILTERS="${FILTERS//$'\n'/'%0A'}"
          FILTERS="${FILTERS//$'\r'/'%0D'}"
          echo "::set-output name=filters::$FILTERS"
      - name: Check for file changes in tested packages
        uses: dorny/paths-filter@v2
        id: tested-filter
        with:
          filters: |
            ${{ steps.tested-filters.outputs.filters }}
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    needs: [changes, build, test]
    if: ${{ needs.changes.outputs.benchmarked-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.benchmarked-packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15.14.0
          cache: npm
      - name: Install monorepo dependencies
        run: npm ci
      - name: Install packages/${{ matrix.package }} dependencies
        working-directory: ./packages/${{ matrix.package }}
        run: npm ci
      - name: Run benchmarks for packages/${{ matrix.package }}
        run: npm run benchmark -- ${{ matrix.package }}
  build:
    name: Compile
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ needs.changes.outputs.all-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.all-packages) }}
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15.14.0
          cache: npm
      - name: Install monorepo dependencies
        working-directory: ./
        run: npm ci
      - name: Install packages/${{ matrix.package }} dependencies
        run: npm ci
      - name: Compile packages/${{ matrix.package }}
        run: npm run compile
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15.14.0
          cache: npm
      - name: Install monorepo dependencies
        run: npm ci
      - name: Run linters
        run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [changes, build]
    if: ${{ needs.changes.outputs.tested-packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.tested-packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15.14.0
          cache: npm
      - name: Install monorepo dependencies
        run: npm ci
      - name: Install packages/${{ matrix.package }} dependencies
        working-directory: ./packages/${{ matrix.package }}
        run: npm ci
      - name: Run test suite for packages/${{ matrix.package }}
        run: npm run coverage -- ${{ matrix.package }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./_reports/coverage/lcov.info
          flags: package-${{ matrix.package }}
