#!/bin/sh
. "$(dirname $0)/_/husky.sh"
. "$(dirname $0)/common.sh"

if [ ! $(IS_MERGING) ]; then
  git stash push --quiet --include-untracked --keep-index
fi

npm run format
git update-index --again

if [ $(DID_STASH) ]; then
  git stash pop --quiet
fi
